server:
  servlet:
    context-path: /gateway
  port: 8081

dubbo:
  application:
    name: micro-gateway-applet
  scan:
    base-packages:
  protocol:
    name: dubbo
    port: 21881
  registry:
    id: my-registry
    address: nacos://10.10.11.2:8848